# Defaults for dbt_unit_test
# unit_test_dir is the folder in your dbt project
# where you keep your versioned unit tests
unit_test_dir: unit_tests

# these must match (or at least be includied in) the settings of your dbt_project.yml
models_dir: models
macros_dir: macros
data_dir: data

# this is the profile that will run your tests
unit_test_profile: unit_test
