version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file: .env

  dbt:
    build: .
    working_dir: /dbt-unit-test/tests/test_project
    env_file: .env
    command: |
      /bin/bash -c "
        pip install -e /dbt-unit-test
        dbt_unit_test --log-level warning"
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /dbt-unit-test
