version: "3"
services:
  db:
    image: postgres
    restart: always
    env_file: .env

  dut-ci:
    image: gitlab.aofl.com:5001/engineering-automation_tools/automation_images/dbt-unit-test-ci:latest
    working_dir: /dbt-unit-test/tests/test_project
    env_file: .env
    command: |
      /bin/bash -c "
        pip install -e /dbt-unit-test
        tox
        dut run --log-level debug
        "
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /dbt-unit-test
